## your first tensorflow program

In [3]:
import tensorflow as tf

a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
with tf.Session() as sess:
    print(sess.run(x))

5


In [4]:
import tensorflow as tf

a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)

writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(x))
writer.close()

5


## Array Operation

### tf.constant

In [5]:
a = tf.constant([2, 2], name='a')

In [6]:
a

<tf.Tensor 'a:0' shape=(2,) dtype=int32>

In [7]:
x = tf.multiply(a, a, name="mul")
with tf.Session() as sess:
    print(sess.run(x))

[4 4]


### tf.zeros

In [9]:
zeros = tf.zeros([2, 3], tf.int32)

In [10]:
with tf.Session() as sess:
    print(sess.run(zeros))

[[0 0 0]
 [0 0 0]]


In [11]:
sess = tf.Session()

In [12]:
sess.run(zeros)

array([[0, 0, 0],
       [0, 0, 0]])

### tf.ones

In [13]:
ones = tf.ones([2, 3])

In [14]:
sess.run(ones)

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [15]:
ones = tf.ones_like([1,2])

In [16]:
sess.run(ones)

array([1, 1])

### tf.fill

In [17]:
sess.run(tf.fill([2, 3], 8))

array([[8, 8, 8],
       [8, 8, 8]])

### tf.lin_space

In [18]:
sess.run(tf.lin_space(10.0, 13, 10))

array([10.      , 10.333333, 10.666667, 11.      , 11.333333, 11.666667,
       12.      , 12.333334, 12.666667, 13.      ], dtype=float32)

### tf.range

In [3]:
import tensorflow as tf
sess = tf.Session()

In [4]:
sess.run(tf.range(3, 18, 2))

array([ 3,  5,  7,  9, 11, 13, 15, 17])

## Randomly Generated Constants

tf.random_normal

tf.truncated_normal

tf.random_uniform

tf.random_shuffle

tf.random_crop

tf.multinomial

tf.random_gamma



In [5]:
tf.set_random_seed(1)

In [6]:
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
with tf.Session() as sess:
	print(sess.run(tf.div(b, a)))             #⇒ [[0 0] [1 1]]
	print(sess.run(tf.divide(b, a)))          #⇒ [[0. 0.5] [1. 1.5]]
	print(sess.run(tf.truediv(b, a)))         #⇒ [[0. 0.5] [1. 1.5]]
	print(sess.run(tf.floordiv(b, a)))        #⇒ [[0 0] [1 1]]
	#print(sess.run(tf.realdiv(b, a)))         #⇒ # Error: only works for real values
	print(sess.run(tf.truncatediv(b, a)))     #⇒ [[0 0] [1 1]]
	print(sess.run(tf.floor_div(b, a))) 


[[0 0]
 [1 1]]
[[0.  0.5]
 [1.  1.5]]
[[0.  0.5]
 [1.  1.5]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]


## TF Data Type

In [7]:
t_1 = [b"apple", b"peach", b"grape"] 	# 1-d arrays are treated like 1-d tensors
tf.zeros_like(t_1)                   # ==> [b'' b'' b'']

<tf.Tensor 'zeros_like:0' shape=(3,) dtype=string>

In [9]:
sess = tf.Session()

In [10]:
sess.run(tf.zeros_like(t_1))

array([b'', b'', b''], dtype=object)

In [11]:
sess.run(tf.ones_like(t_1))

TypeError: Expected string, got 1 of type 'int' instead.

In [13]:
t_2 = [[True, False, False],
  [False, False, True],
  [False, True, False]]         		# 2-d arrays are treated like 2-d tensors

tf.zeros_like(t_2)                  # ==> 3x3 tensor, all elements are False

<tf.Tensor 'zeros_like_4:0' shape=(3, 3) dtype=bool>

In [15]:
sess.run(tf.zeros_like(t_2))

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [16]:
sess.run(tf.ones_like(t_2))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### TF data type can be used seamlessly with numpy